# Genetic Algorithm for Parameter Optimization

This notebook demonstrates:
- Population initialization
- Fitness evaluation
- Selection
- Crossover
- Mutation
- Optimization over generations

In [1]:
import numpy as np
import random

In [2]:
def nn_error(params):
    # Simulated error function (objective to minimize)
    return sum([p**2 for p in params]) + random.random()

In [3]:
population_size = 6
num_generations = 10
mutation_rate = 0.1

# Initial population (each individual has 3 parameters)
population = [np.random.rand(3) for _ in range(population_size)]

print("Initial Population:")
for ind in population:
    print(ind)

Initial Population:
[0.97387014 0.81800798 0.41917807]
[0.61330865 0.27524972 0.65597345]
[0.04831234 0.64174978 0.59756325]
[0.89064026 0.6142269  0.75731378]
[0.95570128 0.29891013 0.56165095]
[0.41414439 0.06147733 0.62395397]


In [4]:
for gen in range(num_generations):

    # Evaluate fitness
    fitness = [nn_error(ind) for ind in population]

    # Sort population based on fitness (lower is better)
    sorted_pop = [x for _, x in sorted(zip(fitness, population))]

    # Select best 2 individuals (elitism)
    new_population = sorted_pop[:2]

    # Generate new individuals
    while len(new_population) < population_size:
        p1, p2 = random.sample(sorted_pop[:4], 2)

        # Crossover (average)
        child = (p1 + p2) / 2

        # Mutation
        if random.random() < mutation_rate:
            child += np.random.normal(0, 0.1, size=3)

        new_population.append(child)

    population = new_population

    print(f"Generation {gen+1}, Best Error: {min(fitness)}")

Generation 1, Best Error: 0.6813297741298241
Generation 2, Best Error: 0.9422644783843218
Generation 3, Best Error: 0.6330485874273947
Generation 4, Best Error: 0.7573304156478035
Generation 5, Best Error: 0.7156476711851855
Generation 6, Best Error: 0.8366708301030172
Generation 7, Best Error: 0.6612870959445127
Generation 8, Best Error: 0.8946472223198985
Generation 9, Best Error: 0.687830138043633
Generation 10, Best Error: 0.6857013764525288


In [5]:
best_solution = min(population, key=nn_error)
print("\nOptimized Parameters:", best_solution)


Optimized Parameters: [0.35877894 0.30678454 0.5217785 ]


## Explanation

### 🔹 Fitness Function
A simple function that simulates neural network error.

### 🔹 Selection
Best individuals are selected based on minimum error.

### 🔹 Crossover
Child is created by averaging two parents.

### 🔹 Mutation
Random noise is added to introduce variation.

### 🔹 Result
The algorithm gradually finds optimized parameters with lower error.